version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT}:${PORT}"
  db:
    container_name: spender-db
    image: mongo:latest
    restart: always
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - ./db_data:/data/db

